name: NoteForge
options:
  bundleIdPrefix: com.33atlas
  deploymentTarget:
    macOS: "12.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "12.0"

packages:
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift
    from: "0.15.0"
  Ink:
    url: https://github.com/JohnSundell/Ink
    from: "0.6.0"
  HotKey:
    url: https://github.com/soffes/HotKey
    from: "0.2.0"
  FileWatcher:
    url: https://github.com/eonist/FileWatcher
    from: "0.2.3"

targets:
  NoteForge:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.33atlas.noteforge
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        PRODUCT_NAME: NoteForge
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: SQLite
      - package: Ink
      - package: HotKey
      - package: FileWatcher
