name: NoteForge
options:
  bundleIdPrefix: com.33atlas
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift
    from: "0.15.0"
  Ink:
    url: https://github.com/JohnSundell/Ink
    from: "0.6.0"
  HotKey:
    url: https://github.com/soffes/HotKey
    from: "0.2.0"
  FileWatcher:
    url: https://github.com/eonist/FileWatcher
    from: "0.2.3"

targets:
  NoteForge:
    type: application
    platform: macOS
    sources:
      - Sources
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.33atlas.noteforge
        PRODUCT_NAME: NoteForge
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_IDENTITY: "-"
        ENABLE_HARDENED_RUNTIME: NO
    dependencies:
      - package: SQLite
        product: SQLite
      - package: Ink
      - package: HotKey
      - package: FileWatcher
