name: NoteForge
options:
  bundleIdPrefix: com.33atlas
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

packages:
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift
    from: "0.15.0"
  Ink:
    url: https://github.com/JohnSundell/Ink
    from: "0.6.0"
  HotKey:
    url: https://github.com/soffes/HotKey
    from: "0.2.0"
  FileWatcher:
    url: https://github.com/eonist/FileWatcher
    from: "0.2.3"

targets:
  NoteForge:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.33atlas.noteforge
        PRODUCT_NAME: NoteForge
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: SQLite
        product: SQLite
      - package: Ink
      - package: HotKey
      - package: FileWatcher

schemes:
  NoteForge:
    build:
      targets:
        NoteForge: all
    run:
      config: Debug
    archive:
      config: Release
